### ISSUE TITLE
Won't compile on Windows

### ISSUE THREAD

**Issue by caecos** [ysig/StrangeAttractor#1]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
parse error: Expected another array element at line 35, column 3
parse error: Expected another array element at line 35, column 3
C:/msys64/Rack-SDK/plugin.mk:9: *** SLUG could not be found in manifest. Arrêt.

**Comment by SteveRussell33** [comment]
Remove the comma at the end of line 33 in plugin.json

**Comment by ysig** [comment]
Fixed
