### ISSUE TITLE
Makefile and plugin.json issues

### ISSUE THREAD

**Issue by SteveRussell33** [ysig/StrangeAttractor#2]
Change the RACK_DIR entry to ``RACK_DIR ?= ../..``
DISTRIBUTABLES can be on one line: ``DISTRIBUTABLES += $(wildcard LICENSE*) res``

Remove the comma at the end of line 33 in the plugin.json manifest.

It will now compile locally.

Edit: Also typo on line 24 (plugin.json) oscilator should be oscillator.

**Comment by caecos** [comment]
Many thanks, it's working good,,,need to learn to code someday...

**Comment by ysig** [comment]
Thanks steveRussell33!
Added all the changes.
